### ISSUE TITLE
Fix the CLI behaviour in a project with no installed dependencies

### ISSUE THREAD

**Issue by alexxander** [webscopeio/mailingui#166]
When running the `init` command in a fresh project with no dependencies installed, the CLI throws the following error

```
node_modules/@mailingui/cli/dist/commands/init.js:26
        if (!installedDependecies[dependency]) {
                                 ^

TypeError: Cannot read properties of undefined (reading 'react-email')
```

It is caused by the following line:
```js
const { dependencies: installedDependecies } = JSON.parse(packageFile);
```

(Also note that there is a typo in the variable name `installedDependecies`)

**Comment by iamhectorsosa** [comment]
Could you elaborate on this? I ran this test and couldn't reproduce this error.

**Comment by alexxander** [comment]
1. Open a clean directory
2. Run `npm init` - this will generate a package.json file with no `dependencies` property
3. After running `npx run @mailingui/cli init`, the error above is thrown as `dependencies` is undefined in the package.json file
