### ISSUE TITLE
Improving Shiki Language performance by Hosting Language

### ISSUE THREAD

**Issue by iamhectorsosa** [webscopeio/mailingui#172]
https://github.com/shikijs/shiki/blob/main/docs/languages.md

**Comment by ChcJohnie** [comment]
Had few minutes without task, so tried fixes I mentioned in #189 
And looks like shiki docs are lying
<img width="557" alt="image" src="https://github.com/webscopeio/mailingui/assets/16903152/f7ecfa0c-00f5-466c-8f04-35a196e08fbf">
Checking if everything works as expected
[Branch](https://github.com/webscopeio/mailingui/tree/shiki-perf)

**Comment by iamhectorsosa** [comment]
Wowwwww! Nice fix, @ChcJohnie

See if we can add more context as JSDocs to these functions and open a PR with the changes.

**Comment by iamhectorsosa** [comment]
Just to follow up, is the default `explanation:true` or `explanation:false`? Did you also test this? Would be interested to know to report to shiki in any case.

**Comment by ChcJohnie** [comment]
Actually highlighter function has default includeExplanation: true, while underlying tokenizer class has includeExplanation:false. But that class is properly documented so I guess it's typing is leaking to upper function. I will recheck and fill issue as it's definitely confusing.

**Comment by iamhectorsosa** [comment]
Great catch! @ChcJohnie

**Comment by ericvalcik** [comment]
Really nice work, I'm happy that you got this working without having to switch libs for the highlighting. Good work @ChcJohnie
