### ISSUE TITLE
CLI installation improvements

### ISSUE THREAD

**Issue by ChcJohnie** [webscopeio/mailingui#204]
Some CLI usage improvements points

- add posibility to adjust tsconfig alias by cli (should be possible?)
- tsconfig alias is incorrect - `"./src/@mailingui/components/index.ts"` working for me with cli defaults
- components could be installed into flat structure (tsx files directly in @mailingui/components folder) so index.ts management can be skipped

**Comment by iamhectorsosa** [comment]
Definitely we need to fix the init option.path to just `./src/mailingui` instead of `./src/@mailingui`

https://github.com/webscopeio/mailingui/blob/main/packages/cli/src/commands/init.ts

**Comment by iamhectorsosa** [comment]
@ericvalcik could you help us with this and redeploy the CLI?

**Comment by ChcJohnie** [comment]
Regarding last point, my current suggestion would be to leave cli as is and update docs.
I experimented with tsconfig alias like `"mailingui/*": ["./src/mailingui/components/*"]`
And importing like `import { Text } from "mailingui/text/Text";`
With this index.ts doesnt have to be added (and managed) manually, and ts looks to be working.

But open to other patterns, just doesnt like docs default 🙂
